"""
secrets.py 导出器
把数据库中的配置还原为与原项目完全兼容的 secrets.py 格式
调用方零改动
"""
from pathlib import Path
from typing import Optional
from sqlmodel import Session, select
from backend.models.config import GlobalSettings, ProviderGroup, ModelEntry, TaskGroup
import pprint


def _to_python_literal(obj) -> str:
    """将对象序列化为合法的 Python 字面量（True/False 而非 true/false）"""
    return pprint.pformat(obj, indent=4, width=120)


_TEMPLATE = '''\
# secrets.py — Auto-generated by llmesh. DO NOT edit manually.

_DEFAULT_TIMEOUT = {default_timeout}

GLOBAL_SETTINGS = {{
    "temperature": {temperature},
    "max_tokens": {max_tokens},
    "max_retries": {max_retries},
    "fault_duration": {fault_duration},
    "default_timeout": _DEFAULT_TIMEOUT,
    "timeout_retries": {timeout_retries},
    "timeout_step": {timeout_step},
    "rate_limit_cooldown": {rate_limit_cooldown},
    {thinking_timeout_line}
}}

MODEL_POOL_RAW = {model_pool_raw}

TASK_GROUPS = {task_groups}
'''


def _build_model_entry(entry: ModelEntry, group: ProviderGroup) -> dict | str:
    """构造单个模型条目，若只有 model 字段则简化为字符串"""
    import json as _json
    extra_body = entry.get_extra_body()
    effective_priority = entry.priority if entry.priority is not None else group.priority

    # 合并 tags：模型自身 tags + billing_mode 自动注入
    base_tags: list = []
    if entry.tags:
        try:
            base_tags = _json.loads(entry.tags)
        except Exception:
            pass
    if group.billing_mode and group.billing_mode not in base_tags:
        base_tags = base_tags + [group.billing_mode]
    effective_tags = base_tags if base_tags else None

    has_overrides = any([
        entry.weight is not None and entry.weight != group.weight,
        entry.timeout is not None and entry.timeout != group.timeout,
        entry.remark,
        entry.supports_thinking,
        entry.is_thinking_only,
        entry.is_vision,
        effective_tags,
        extra_body,
        effective_priority != 0,
        entry.thinking_timeout is not None,
    ])
    if not has_overrides:
        return entry.model
    d: dict = {"model": entry.model}
    if entry.weight is not None and entry.weight != group.weight:
        d["weight"] = entry.weight
    if entry.timeout is not None and entry.timeout != group.timeout:
        d["timeout"] = entry.timeout
    if entry.remark:
        d["remark"] = entry.remark
    if entry.supports_thinking:
        d["supports_thinking"] = True
    if entry.is_thinking_only:
        d["is_thinking_only"] = True
    if entry.is_vision:
        d["is_vision"] = True
    if effective_tags:
        d["tags"] = effective_tags
    if effective_priority != 0:
        d["priority"] = effective_priority
    if extra_body:
        d["extra_body"] = extra_body
    if entry.thinking_timeout is not None:
        d["thinking_timeout"] = entry.thinking_timeout
    return d


def export_secrets(session: Session, output_path: Optional[str | Path] = None) -> str:
    """
    从数据库生成 secrets.py 内容，并可选写入文件。
    返回生成的字符串内容。
    """
    gs = session.exec(select(GlobalSettings)).first() or GlobalSettings()
    groups = session.exec(
        select(ProviderGroup).where(ProviderGroup.enabled == True)  # noqa: E712
    ).all()

    pool_raw = []
    for group in groups:
        entries = session.exec(
            select(ModelEntry)
            .where(ModelEntry.group_id == group.id)
            .where(ModelEntry.enabled == True)  # noqa: E712
        ).all()
        if not entries:
            continue

        models_list = [_build_model_entry(e, group) for e in entries]

        g: dict = {
            "vendor": group.vendor,
            "api_key": group.api_key,
            "base_url": group.base_url,
        }
        if group.weight != 1:
            g["weight"] = group.weight
        if group.priority != 0:
            g["priority"] = group.priority
        if group.timeout != 60:
            g["timeout"] = group.timeout
        if group.remark:
            g["remark"] = group.remark
        g["models"] = models_list
        pool_raw.append(g)

    # 任务组
    task_groups_raw = []
    tgs = session.exec(
        select(TaskGroup).where(TaskGroup.enabled == True)  # noqa: E712
    ).all()
    for tg in tgs:
        entry: dict = {"name": tg.name}
        if tg.display_name:
            entry["display_name"] = tg.display_name
        pinned = tg.get_pinned()
        if pinned:
            entry["pinned"] = pinned
        exc_tags = tg.get_exclude_tags()
        if exc_tags:
            entry["exclude_tags"] = exc_tags
        soft_tags = tg.get_tags()
        if soft_tags:
            entry["tags"] = soft_tags
        prefer = tg.get_prefer()
        if prefer:
            entry["prefer"] = prefer
        thinking = tg.get_thinking()
        if thinking is not None:
            entry["thinking"] = thinking
        if tg.remark:
            entry["remark"] = tg.remark
        task_groups_raw.append(entry)

    if gs.default_thinking_timeout is not None:
        thinking_timeout_line = f'"default_thinking_timeout": {gs.default_thinking_timeout},'
    else:
        thinking_timeout_line = ""
    content = _TEMPLATE.format(
        default_timeout=gs.default_timeout,
        temperature=gs.temperature,
        max_tokens=gs.max_tokens,
        max_retries=gs.max_retries,
        fault_duration=gs.fault_duration,
        timeout_retries=gs.timeout_retries,
        timeout_step=gs.timeout_step,
        rate_limit_cooldown=gs.rate_limit_cooldown,
        thinking_timeout_line=thinking_timeout_line,
        model_pool_raw=_to_python_literal(pool_raw),
        task_groups=_to_python_literal(task_groups_raw),
    )

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    return content
