"""
secrets.py 导出器
把数据库中的配置还原为与原项目完全兼容的 secrets.py 格式
调用方零改动
"""
from pathlib import Path
from typing import Optional
from sqlmodel import Session, select
from backend.models.config import GlobalSettings, ProviderGroup, ModelEntry
import pprint


def _to_python_literal(obj) -> str:
    """将对象序列化为合法的 Python 字面量（True/False 而非 true/false）"""
    return pprint.pformat(obj, indent=4, width=120)


_TEMPLATE = '''\
# secrets.py — Auto-generated by llmesh. DO NOT edit manually.

_DEFAULT_TIMEOUT = {default_timeout}

GLOBAL_SETTINGS = {{
    "temperature": {temperature},
    "max_tokens": {max_tokens},
    "max_retries": {max_retries},
    "fault_duration": {fault_duration},
    "default_timeout": _DEFAULT_TIMEOUT,
    "timeout_retries": {timeout_retries},
    "timeout_step": {timeout_step},
    "rate_limit_cooldown": {rate_limit_cooldown},
}}

MODEL_POOL_RAW = {model_pool_raw}
'''


def _build_model_entry(entry: ModelEntry, group: ProviderGroup) -> dict | str:
    """构造单个模型条目，若只有 model 字段则简化为字符串"""
    extra_body = entry.get_extra_body()
    has_overrides = any([
        entry.weight is not None and entry.weight != group.weight,
        entry.timeout is not None and entry.timeout != group.timeout,
        entry.remark,
        entry.supports_thinking,
        entry.is_thinking_only,
        extra_body,
    ])
    if not has_overrides:
        return entry.model
    d: dict = {"model": entry.model}
    if entry.weight is not None and entry.weight != group.weight:
        d["weight"] = entry.weight
    if entry.timeout is not None and entry.timeout != group.timeout:
        d["timeout"] = entry.timeout
    if entry.remark:
        d["remark"] = entry.remark
    if entry.supports_thinking:
        d["supports_thinking"] = True
    if entry.is_thinking_only:
        d["is_thinking_only"] = True
    if extra_body:
        d["extra_body"] = extra_body
    return d


def export_secrets(session: Session, output_path: Optional[str | Path] = None) -> str:
    """
    从数据库生成 secrets.py 内容，并可选写入文件。
    返回生成的字符串内容。
    """
    gs = session.exec(select(GlobalSettings)).first() or GlobalSettings()
    groups = session.exec(
        select(ProviderGroup).where(ProviderGroup.enabled == True)  # noqa: E712
    ).all()

    pool_raw = []
    for group in groups:
        entries = session.exec(
            select(ModelEntry)
            .where(ModelEntry.group_id == group.id)
            .where(ModelEntry.enabled == True)  # noqa: E712
        ).all()
        if not entries:
            continue

        models_list = [_build_model_entry(e, group) for e in entries]

        g: dict = {
            "vendor": group.vendor,
            "api_key": group.api_key,
            "base_url": group.base_url,
        }
        if group.weight != 1:
            g["weight"] = group.weight
        if group.remark:
            g["remark"] = group.remark
        g["models"] = models_list
        pool_raw.append(g)

    content = _TEMPLATE.format(
        default_timeout=gs.default_timeout,
        temperature=gs.temperature,
        max_tokens=gs.max_tokens,
        max_retries=gs.max_retries,
        fault_duration=gs.fault_duration,
        timeout_retries=gs.timeout_retries,
        timeout_step=gs.timeout_step,
        rate_limit_cooldown=gs.rate_limit_cooldown,
        model_pool_raw=_to_python_literal(pool_raw),
    )

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    return content
